apiVersion: v1
kind: Service
metadata:
  annotations:
    move2kube.service.expose: "true"
  creationTimestamp: null
  labels:
    io.move2kube.service: redis
  name: redis
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    protocol: TCP
    targetPort: 55555
  selector:
    io.move2kube.service: redis
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
